services:
  db:
    image: mongo:7.0
    restart: unless-stopped
    container_name: mongodb
    volumes:
      - db-data:/data/db/
    ports:
      - "127.0.0.1:27017:27017"
  server:
    restart: unless-stopped
    container_name: ripes_server
    build:
      context: ./backend
      dockerfile: Dockerfile_server
    ports:
      - "127.0.0.1:3000:3000"
  client:
    restart: unless-stopped
    container_name: ripes_client
    build:
      context: ./frontend
      dockerfile: Dockerfile_client
    ports:
      - "127.0.0.1:8080:80"
volumes:
  db-data:
