FROM ubuntu:20.04
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install npm -f -y
RUN apt-get install curl -f -y
RUN apt-get install mongodb-clients -f -y
ENV NODE_VERSION=16.13.0
RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"

WORKDIR ./server

COPY ./server .

RUN npm install

CMD mongo admin --host mongodb:27017 --eval "db.createUser({user: 'ripes_server', pwd:'a_real_password', roles:['userAdminAnyDatabase'], mechanisms:['SCRAM-SHA-1']})"; node ./index.js
